version: '3.8'

services:
  db:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: DBName
      POSTGRES_USER: DBUser
      POSTGRES_PASSWORD: DBPassword
    ports:
      - "5432:5432"
    networks:
      - dex-network

  # solidity-development:
  #   build:
  #     context: ./contracts
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./contracts:/app
  #   command: truffle develop
  #   networks:
  #     - dex-network

  api: 
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: DBUser
      DB_PASSWORD: DBPassword
      DB_NAME: DBName
    networks:
      - dex-network

  next-app:
    build:
      context: ./next-app
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    networks:
      - dex-network

volumes:
  db-data:

networks:
  dex-network:
    driver: bridge
