version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - ./api/.env
    ports:
      - "5001:5000"
    networks:
      - dex-network

  next-app:
    build:
      context: ./next-app
      dockerfile: Dockerfile
    env_file:
      - ./next-app/.env
    ports:
      - "3000:3000"
    networks:
      - dex-network

networks:
  dex-network:
    driver: bridge
