[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
gas_reports = ["*"]

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/foundry-upgrades/=lib/openzeppelin-foundry-upgrades/src/"
]

[rpc_endpoints]
sepolia = "${API_KEY_ALCHEMY_SEPOLIA}"
sepolia_infura = "${API_KEY_INFURA_SEPOLIA}"
mainnet = "${API_KEY_ALCHEMY_MAINNET}"
mainnet_infura = "${API_KEY_INFURA_MAINNET}"

[etherscan]
polygon-amoy = { key = "${AMOY_API_KEY}", url = "https://www.oklink.com/api/explorer/v1/contract/verify/async/api/polygonAmoy" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options